   ### get all
### passing paramters for now  page and limit only
http://localhost:3000/bots

### Get by botId
http://localhost:3000/bots/xyz


### Get by owner(email address)
http://localhost:3000/bots/owner/s.bb@gmail.com


### 
POST http://localhost:3000/bots
Content-Type:  application/json

{
    "botName": "Mark2",
    "botDesc": "Mark3 is a test bot",
    "owner": "s.bb@gmail.com"
}

### Update by email
PUT http://localhost:3000/bots/bot_mdqa1e6y_MMF8T9
Content-Type:  application/json

{
  "botName": "Mark1-updated"
}


### Delete by email
DELETE http://localhost:3000/bots/bot_mdq9tfo3_1IL1QL
`