/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HubRouteImport } from './routes/Hub'
import { Route as HomeRouteImport } from './routes/Home'
import { Route as AgentRouteImport } from './routes/Agent'
import { Route as IndexRouteImport } from './routes/index'

const HubRoute = HubRouteImport.update({
  id: '/Hub',
  path: '/Hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/Home',
  path: '/Home',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/Agent',
  path: '/Agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Agent': typeof AgentRoute
  '/Home': typeof HomeRoute
  '/Hub': typeof HubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Agent': typeof AgentRoute
  '/Home': typeof HomeRoute
  '/Hub': typeof HubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Agent': typeof AgentRoute
  '/Home': typeof HomeRoute
  '/Hub': typeof HubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Agent' | '/Home' | '/Hub'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Agent' | '/Home' | '/Hub'
  id: '__root__' | '/' | '/Agent' | '/Home' | '/Hub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  HomeRoute: typeof HomeRoute
  HubRoute: typeof HubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Hub': {
      id: '/Hub'
      path: '/Hub'
      fullPath: '/Hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Home': {
      id: '/Home'
      path: '/Home'
      fullPath: '/Home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Agent': {
      id: '/Agent'
      path: '/Agent'
      fullPath: '/Agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  HomeRoute: HomeRoute,
  HubRoute: HubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
