/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as apphubHubOverviewRouteImport } from './routes/(app)/(hub)/hub-overview'
import { Route as appagentsAgentOverviewRouteImport } from './routes/(app)/(agents)/agent-overview'
import { Route as appchatChatboxBotIdRouteImport } from './routes/(app)/(chat)/chatbox.$botId'
import { Route as appagentsAgentDetailsBotIdRouteImport } from './routes/(app)/(agents)/agent-details.$botId'
import { Route as appagentsAgentToolsToolIdRouteImport } from './routes/(app)/(agents)/agent.tools.$toolId'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const apphubHubOverviewRoute = apphubHubOverviewRouteImport.update({
  id: '/(hub)/hub-overview',
  path: '/hub-overview',
  getParentRoute: () => appRouteRoute,
} as any)
const appagentsAgentOverviewRoute = appagentsAgentOverviewRouteImport.update({
  id: '/(agents)/agent-overview',
  path: '/agent-overview',
  getParentRoute: () => appRouteRoute,
} as any)
const appchatChatboxBotIdRoute = appchatChatboxBotIdRouteImport.update({
  id: '/(chat)/chatbox/$botId',
  path: '/chatbox/$botId',
  getParentRoute: () => appRouteRoute,
} as any)
const appagentsAgentDetailsBotIdRoute =
  appagentsAgentDetailsBotIdRouteImport.update({
    id: '/(agents)/agent-details/$botId',
    path: '/agent-details/$botId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appagentsAgentToolsToolIdRoute =
  appagentsAgentToolsToolIdRouteImport.update({
    id: '/(agents)/agent/tools/$toolId',
    path: '/agent/tools/$toolId',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof appIndexRoute
  '/agent-overview': typeof appagentsAgentOverviewRoute
  '/hub-overview': typeof apphubHubOverviewRoute
  '/agent-details/$botId': typeof appagentsAgentDetailsBotIdRoute
  '/chatbox/$botId': typeof appchatChatboxBotIdRoute
  '/agent/tools/$toolId': typeof appagentsAgentToolsToolIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof appIndexRoute
  '/agent-overview': typeof appagentsAgentOverviewRoute
  '/hub-overview': typeof apphubHubOverviewRoute
  '/agent-details/$botId': typeof appagentsAgentDetailsBotIdRoute
  '/chatbox/$botId': typeof appchatChatboxBotIdRoute
  '/agent/tools/$toolId': typeof appagentsAgentToolsToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/(agents)/agent-overview': typeof appagentsAgentOverviewRoute
  '/(app)/(hub)/hub-overview': typeof apphubHubOverviewRoute
  '/(app)/(agents)/agent-details/$botId': typeof appagentsAgentDetailsBotIdRoute
  '/(app)/(chat)/chatbox/$botId': typeof appchatChatboxBotIdRoute
  '/(app)/(agents)/agent/tools/$toolId': typeof appagentsAgentToolsToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/agent-overview'
    | '/hub-overview'
    | '/agent-details/$botId'
    | '/chatbox/$botId'
    | '/agent/tools/$toolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/agent-overview'
    | '/hub-overview'
    | '/agent-details/$botId'
    | '/chatbox/$botId'
    | '/agent/tools/$toolId'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(app)/'
    | '/(app)/(agents)/agent-overview'
    | '/(app)/(hub)/hub-overview'
    | '/(app)/(agents)/agent-details/$botId'
    | '/(app)/(chat)/chatbox/$botId'
    | '/(app)/(agents)/agent/tools/$toolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(hub)/hub-overview': {
      id: '/(app)/(hub)/hub-overview'
      path: '/hub-overview'
      fullPath: '/hub-overview'
      preLoaderRoute: typeof apphubHubOverviewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(agents)/agent-overview': {
      id: '/(app)/(agents)/agent-overview'
      path: '/agent-overview'
      fullPath: '/agent-overview'
      preLoaderRoute: typeof appagentsAgentOverviewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(chat)/chatbox/$botId': {
      id: '/(app)/(chat)/chatbox/$botId'
      path: '/chatbox/$botId'
      fullPath: '/chatbox/$botId'
      preLoaderRoute: typeof appchatChatboxBotIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(agents)/agent-details/$botId': {
      id: '/(app)/(agents)/agent-details/$botId'
      path: '/agent-details/$botId'
      fullPath: '/agent-details/$botId'
      preLoaderRoute: typeof appagentsAgentDetailsBotIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(agents)/agent/tools/$toolId': {
      id: '/(app)/(agents)/agent/tools/$toolId'
      path: '/agent/tools/$toolId'
      fullPath: '/agent/tools/$toolId'
      preLoaderRoute: typeof appagentsAgentToolsToolIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appagentsAgentOverviewRoute: typeof appagentsAgentOverviewRoute
  apphubHubOverviewRoute: typeof apphubHubOverviewRoute
  appagentsAgentDetailsBotIdRoute: typeof appagentsAgentDetailsBotIdRoute
  appchatChatboxBotIdRoute: typeof appchatChatboxBotIdRoute
  appagentsAgentToolsToolIdRoute: typeof appagentsAgentToolsToolIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appagentsAgentOverviewRoute: appagentsAgentOverviewRoute,
  apphubHubOverviewRoute: apphubHubOverviewRoute,
  appagentsAgentDetailsBotIdRoute: appagentsAgentDetailsBotIdRoute,
  appchatChatboxBotIdRoute: appchatChatboxBotIdRoute,
  appagentsAgentToolsToolIdRoute: appagentsAgentToolsToolIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
