### get all


### passing paramters for now  page and limit only
http://localhost:3000/bots
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxZWZlNDI3M2M2NzBhMTYxNjFhOCIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoiTWFyazEiLCJpYXQiOjE3NTgzODE0MjcsImV4cCI6MTc1ODQ2NzgyN30.JSDnKJ1jnhm-7Wao8lkpdwb2_a-aN7jErLPFhdOxEQM


### Get by botId
http://localhost:3000/bots/bot_mfsfekoi_Z96YMW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxZWZlNDI3M2M2NzBhMTYxNjFhOCIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoiTWFyazEiLCJpYXQiOjE3NTg0NDAyNDYsImV4cCI6MTc1ODUyNjY0Nn0.nAZbO0IqYNAUTr2FZZkj3gxH45QhsnHSDUrMrcAbkVc


### Get by owner(email address)
http://localhost:3000/bots/owner/shubhambankar65@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxZWZlNDI3M2M2NzBhMTYxNjFhOCIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoiTWFyazEiLCJpYXQiOjE3NTgzODE0MjcsImV4cCI6MTc1ODQ2NzgyN30.JSDnKJ1jnhm-7Wao8lkpdwb2_a-aN7jErLPFhdOxEQM


### 
POST http://localhost:3000/botsp
Content-Type:  application/json

{
    "botName": "Mark2",
    "botDesc": "Mark3 is a test bot",
    "owner": "s.bb@gmail.com"
}


### Update by email
PUT http://localhost:3000/bots/bot_mdqa1e6y_MMF8T9
Content-Type:  application/json

{
  "botName": "Mark1-updated"
}


### Delete by email
DELETE http://localhost:3000/bots/bot_mdq9tfo3_1IL1QL
`