@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQwYWQ2MDA3NWUwMTAzYTAxNTZlNiIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoiTWFyazEiLCJpYXQiOjE3NjQ1MDY0NDgsImV4cCI6MTc2NDU5Mjg0OH0.rwmJdQ7vik6U8fqP7Zso48rgktbbwbze4LQVA-89TYc
### get all


### passing paramters for now  page and limit only
http://localhost:3000/bots
Authorization: Bearer {{token}}


### Get by botId
http://localhost:3000/bots/bot_mfv2vn5t_ZTPOE4
Authorization: Bearer {{token}}

### Get by owner(email address)
http://localhost:3000/bots/owner/shubhambankar65@gmail.com
Authorization: Bearer {{token}}


### 
POST http://localhost:3000/bots
Content-Type:  application/json
Authorization: Bearer {{token}}

{
    "botName": "Mark2",
    "botDesc": "Mark3 is a test bot",
    "owner": "shubhambankar65@gmail.com"
}


### Update by email
PUT http://localhost:3000/bots/bot_milpmq1o_21MODR
Content-Type:  application/json
Authorization: Bearer {{token}}

{
  "toolModel": "Mark1-updated"
}


### Delete by email
DELETE http://localhost:3000/bots/bot_mdq9tfo3_1IL1QL
`