@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQwYWQ2MDA3NWUwMTAzYTAxNTZlNiIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsImlhdCI6MTc3MTE2NjE3NSwiZXhwIjoxNzcxMjUyNTc1fQ.Bw8yNx1LOPGBCiWNEudeH_cPDS-_X458Al6kaJojLU8
### get all

POST http://localhost:3000/auth
Content-Type:  application/json

{
    "email": "shubhambankar65@gmail.com",
    "password": "Testing@123"
}

###
http://localhost:3000/bots/


### Example tool calling a weather API  (in testing phase)
POST http://localhost:3000/chat
Content-Type:  application/json

{
   "botId":"bot_mdqa1e6y_MMF8T9", 
   "question":"what is weather in Pune"
}

### 
POST http://localhost:3000/chat
Content-Type:  application/json
Authorization: Bearer {{token}}

{
   "botId":"bot_milpmq1o_21MODR", 
   "question":"what is weather in Pune"
}


