
###
POST http://localhost:3000/auth
Content-Type:  application/json

{
    "email": "shubhambankar65@gmail.com",
    "password": "Testing@123"
}

### Example tool calling a weather API  (in testing phase)
POST http://localhost:3000/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzMxZWZlNDI3M2M2NzBhMTYxNjFhOCIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsImlhdCI6MTc2Njk0OTA3NSwiZXhwIjoxNzY3MDM1NDc1fQ.cvH7ss4CJqZgbUPnyMTvRysBIe1GXvBIrjDEE8er5Tw
Content-Type:  application/json

{
   "botId":"bot_mfsfekoi_Z96YMW", 
   "question":"what is weather in mumbai"
}

### 
POST http://localhost:3000/chat
Content-Type:  application/json
Authorization: Bearer {{token}}

{
   "botId":"bot_milpmq1o_21MODR", 
   "question":"what is weather in Pune"
}


