### get all


### passing paramters for now  page and limit only
http://localhost:3000/users


### Get by email
http://localhost:3000/users/email/s.b@gmail.com


### Get by username
http://localhost:3000/users/username/string


### 
POST http://localhost:3000/users
Content-Type:  application/json

{
    "firstName": "shubham",
    "lastName": "Bankar",
    "userName":"Mark1",
    "email": "shubhambankar65@gmail.com",
    "password": "Testing@123"
}


### 
POST http://localhost:3000/auth
Content-Type:  application/json

{
    "email": "shubhambankar65@gmail.com",
    "password": "Testing@123"
}


### Update by email
PUT http://localhost:3000/users/email/s.b@gmail.com
Content-Type:  application/json

{
    "firstName": "string",
    "lastName": "string",
    "userName": "string",
    "email": "s.b@gmail.com",
    "password": "string"
}


### Delete by email
DELETE http://localhost:3000/users/email/s.b@gmail.com