@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQwYWQ2MDA3NWUwMTAzYTAxNTZlNiIsImVtYWlsIjoic2h1YmhhbWJhbmthcjY1QGdtYWlsLmNvbSIsInVzZXJOYW1lIjoiTWFyazEiLCJpYXQiOjE3NjQ1MDY0NDgsImV4cCI6MTc2NDU5Mjg0OH0.rwmJdQ7vik6U8fqP7Zso48rgktbbwbze4LQVA-89TYc
### get all


### passing paramters for now  page and limit only
http://localhost:3000/users


### Get by email
http://localhost:3000/users/email/s.b@gmail.com


### Get by username
http://localhost:3000/users/username/string


### 
POST http://localhost:3000/users
Content-Type:  application/json
Authorization: Bearer {{token}}

{
    "firstName": "shubham",
    "lastName": "Bankar",
    "email": "shubhambankar65-1@gmail.com",
    "password": "Testing@123"
}


### 
POST http://localhost:3000/auth
Content-Type:  application/json

{
    "email": "shubhambankar65@gmail.com",
    "password": "Testing@123"
}


### Update by email
PUT http://localhost:3000/users/email/s.b@gmail.com
Content-Type:  application/json

{
    "firstName": "string",
    "lastName": "string",
    "email": "s.b@gmail.com",
    "password": "string"
}


### Delete by email
DELETE http://localhost:3000/users/email/s.b@gmail.com