import { classifyFile, classifyPath } from "../classify";

describe("classifyPath", () => {
  it.each([
    // test
    ["src/user.test.ts", "test"],
    ["src/user.spec.tsx", "test"],
    ["src/__tests__/user.ts", "test"],
    ["test/helpers.js", "test"],
    ["packages/a/tests/x.ts", "test"],
    // config
    ["package.json", "config"],
    ["tsconfig.json", "config"],
    ["tsconfig.build.json", "config"],
    ["vite.config.ts", "config"],
    ["webpack.config.js", "config"],
    [".eslintrc.cjs", "config"],
    [".env.example", "config"],
    ["Dockerfile", "config"],
    ["docker-compose.yml", "config"],
    [".github/workflows/ci.yml", "config"],
    ["pom.xml", "config"],
    ["src/Api.csproj", "config"],
    ["appsettings.Development.json", "config"],
    // docs
    ["README.md", "docs"],
    ["docs/architecture.txt", "docs"],
    // schema
    ["prisma/schema.prisma", "schema"],
    ["db/init.sql", "schema"],
    ["api/openapi.yaml", "schema"],
    ["schema/user.graphql", "schema"],
    // generated (by path)
    ["src/routeTree.gen.ts", "generated"],
    ["src/api.generated.ts", "generated"],
    ["src/__generated__/types.ts", "generated"],
    ["src/user.test.ts.snap", "generated"],
    // source
    ["src/services/user.ts", "source"],
    ["server.js", "source"],
    ["src/components/UserCard.tsx", "source"],
    // a folder that merely contains "test" in its name is not a test dir
    ["test-fixtures/sample/app.js", "source"],
  ])("%s -> %s", (path, expected) => {
    expect(classifyPath(path)).toBe(expected);
  });

  it("puts test before config/docs when several rules match", () => {
    expect(classifyPath("test/package.json")).toBe("test");
    expect(classifyPath("tests/README.md")).toBe("test");
  });
});

describe("classifyFile", () => {
  it("detects generated files from the header", () => {
    expect(classifyFile({ path: "src/a.ts", content: "// AUTO-GENERATED — do not edit\nexport const a = 1;" })).toBe("generated");
    expect(classifyFile({ path: "src/a.ts", content: "/* @generated */\nexport {}" })).toBe("generated");
    expect(classifyFile({ path: "src/a.go", content: "// Code generated by protoc. DO NOT EDIT.\npackage x" })).toBe("generated");
  });

  it("only looks at the top of the file", () => {
    const body = `${"const x = 1;\n".repeat(30)}// do not edit this later\n`;
    expect(classifyFile({ path: "src/a.ts", content: body })).toBe("source");
  });

  it("falls back to the path category", () => {
    expect(classifyFile({ path: "src/a.ts", content: "export const a = 1;" })).toBe("source");
    expect(classifyFile({ path: "src/a.test.ts", content: "it('x', () => {})" })).toBe("test");
  });
});
