import type { FileCategory } from "../core/types";

/**
 * Category of a file, from its path and (for "generated") its first lines.
 * Precedence: generated → test → config → docs → schema → source.
 */

const basename = (p: string): string => p.split("/").pop() ?? p;
const segments = (p: string): string[] => p.split("/").slice(0, -1);

const TEST_DIRS = new Set(["__tests__", "test", "tests", "__mocks__", "e2e", "cypress"]);
const isTest = (p: string): boolean => {
  const name = basename(p).toLowerCase();
  if (/\.(test|spec)\.[^.]+$/.test(name)) return true;
  return segments(p).some((s) => TEST_DIRS.has(s.toLowerCase()));
};

const isGeneratedPath = (p: string): boolean => {
  const name = basename(p).toLowerCase();
  if (/\.(gen|generated)\.[^.]+$/.test(name)) return true; // routeTree.gen.ts, foo.generated.ts
  if (/\.snap$/.test(name)) return true;                    // jest snapshots
  if (/(\.pb\.|_pb\.|_pb2\.)/.test(name)) return true;      // protobuf output
  return segments(p).some((s) => s === "__generated__" || s === "generated");
};

const GENERATED_HEADER =
  /auto[- ]?generated|do not edit|@generated|this file (is|was) (automatically )?generated|code generated by/i;

const hasGeneratedHeader = (content: string): boolean =>
  GENERATED_HEADER.test(content.split("\n", 8).join("\n").slice(0, 600));

const CONFIG_NAMES = new Set([
  "package.json", ".gitignore", ".dockerignore", "dockerfile", "makefile",
  "pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts",
  ".env.example", ".env.sample", ".env.template", ".env.dist",
  ".gitlab-ci.yml", ".editorconfig", "nodemon.json",
]);
const CONFIG_PATTERNS: RegExp[] = [
  /^tsconfig.*\.json$/, /^jsconfig.*\.json$/,
  /^\.eslintrc(\..+)?$/, /^eslint\.config\..+$/, /^\.prettierrc(\..+)?$/,
  /^(vite|webpack|rollup|jest|vitest|babel|tailwind|postcss|next|nuxt|svelte)\.config\..+$/,
  /^docker(file|-compose).*$/,
  /\.csproj$/, /\.sln$/,
  /^appsettings.*\.json$/, /^application.*\.(ya?ml|properties)$/,
];
const isConfig = (p: string): boolean => {
  const name = basename(p).toLowerCase();
  if (CONFIG_NAMES.has(name) || CONFIG_PATTERNS.some((re) => re.test(name))) return true;
  const dirs = segments(p);
  // CI definitions: .github/workflows/*.yml, .circleci/*
  return (dirs.includes(".github") && dirs.includes("workflows")) || dirs.includes(".circleci");
};

const isDocs = (p: string): boolean =>
  /\.(md|mdx|rst)$/i.test(p) || segments(p).some((s) => s.toLowerCase() === "docs");

const isSchema = (p: string): boolean => {
  const name = basename(p).toLowerCase();
  return /\.(prisma|sql|graphql|gql|proto)$/.test(name) || /^(openapi|swagger)\..+$/.test(name);
};

/** Category from the path alone (never returns "generated" — that needs content for the header rule, see classifyFile). */
export const classifyPath = (p: string): FileCategory => {
  if (isGeneratedPath(p)) return "generated";
  if (isTest(p)) return "test";
  if (isConfig(p)) return "config";
  if (isDocs(p)) return "docs";
  if (isSchema(p)) return "schema";
  return "source";
};

export const classifyFile = ({ path, content }: { path: string; content: string }): FileCategory => {
  const byPath = classifyPath(path);
  if (byPath === "generated") return byPath;
  // A generated header wins over every other category: the file is not meant to be read or edited.
  if (hasGeneratedHeader(content)) return "generated";
  return byPath;
};
